const INACTIVITY_TIMEOUT = 5 * 60 * 1000 // 5 mins
const MAX_SINGLE_FRAME_CONTENT_LENGTH = 26 * 1024 // hard max 32kb
const WORMHOLE_CLIENT_RESPONSE_TIMEOUT = 25 * 1000 // 25s

module.exports = {
  INACTIVITY_TIMEOUT,
  MAX_SINGLE_FRAME_CONTENT_LENGTH,
  WORMHOLE_CLIENT_RESPONSE_TIMEOUT,
}

